# theme.toml template for a Hugo theme
# See https://github.com/spf13/hugoThemes#themetoml for an example

name = "BMF Hugo Theme"
license = "MIT"
licenselink = "https://github.com/schmooser/bmf-hugo-theme/blob/master/LICENSE.md"
description = "Better Motherfucking Theme for Hugo static website generator"
homepage = "http://ora600.ru/theme"
tags = ["", ""]
features = ["", ""]
min_version = 0.13

[author]
  name = "Pavel Popov"
  homepage = "http://ora600.ru"

# If porting an existing theme
[original]
  name = "Better Motherfucking Website"
  homepage = "http://bettermotherfuckingwebsite.com"
  repo = ""
